JMP main;
main: ;
SET A 0;
for_start_1: ;
JLT A 10 for_body_2;
JMP for_end_3;
for_body_2: ;
WRITESTR "O valor é: ";
PRINTLN A;
SET B 1;
ADD A B;
JMP for_start_1;
for_end_3: ;
SET C 1;
JNE C 0 if_true_5;
JMP if_false_6;
if_true_5: ;
WRITESTR "TESTE APROVADO";
PRINTLN "";
JMP if_end_7;
if_false_6: ;
if_end_7: ;
WRITESTR "LOOP FINALIZADO:";
PRINTLN "";
while_start_8: ;
JNE 1 0 while_body_9;
JMP while_end_10;
while_body_9: ;
UPDATEGUI;
JMP while_start_8;
while_end_10: ;
HALT;